// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using WorkflowCore.Persistence.Oracle;

#nullable disable

namespace WorkflowCore.Persistence.Oracle.Migrations
{
    [DbContext(typeof(OracleContext))]
    partial class OracleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorkflowCore.Persistence.EntityFramework.Models.PersistedEvent", b =>
                {
                    b.Property<long>("PersistenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("PERSISTENCEID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PersistenceId"));

                    b.Property<string>("EventData")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("EVENTDATA");

                    b.Property<Guid>("EventId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("EVENTID");

                    b.Property<string>("EventKey")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("EVENTKEY");

                    b.Property<string>("EventName")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("EVENTNAME");

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("EVENTTIME");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ISPROCESSED");

                    b.HasKey("PersistenceId");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("EventTime");

                    b.HasIndex("IsProcessed");

                    b.HasIndex("EventName", "EventKey");

                    b.ToTable("WF_EVENT", "HLV_EMAIL_PRO");
                });

            modelBuilder.Entity("WorkflowCore.Persistence.EntityFramework.Models.PersistedExecutionError", b =>
                {
                    b.Property<long>("PersistenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("PERSISTENCEID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PersistenceId"));

                    b.Property<DateTime>("ErrorTime")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("ERRORTIME");

                    b.Property<string>("ExecutionPointerId")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("EXECUTIONPOINTERID");

                    b.Property<string>("Message")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("MESSAGE");

                    b.Property<string>("WorkflowId")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("WORKFLOWID");

                    b.HasKey("PersistenceId");

                    b.ToTable("WF_EXECUTIONERROR", "HLV_EMAIL_PRO");
                });

            modelBuilder.Entity("WorkflowCore.Persistence.EntityFramework.Models.PersistedExecutionPointer", b =>
                {
                    b.Property<long>("PersistenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("PERSISTENCEID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PersistenceId"));

                    b.Property<bool>("Active")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ACTIVE");

                    b.Property<string>("Children")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CHILDREN");

                    b.Property<string>("ContextItem")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CONTEXTITEM");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("ENDTIME");

                    b.Property<string>("EventData")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("EVENTDATA");

                    b.Property<string>("EventKey")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("EVENTKEY");

                    b.Property<string>("EventName")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("EVENTNAME");

                    b.Property<bool>("EventPublished")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("EVENTPUBLISHED");

                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("ID");

                    b.Property<string>("Outcome")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("OUTCOME");

                    b.Property<string>("PersistenceData")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("PERSISTENCEDATA");

                    b.Property<string>("PredecessorId")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("PREDECESSORID");

                    b.Property<int>("RetryCount")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("RETRYCOUNT");

                    b.Property<string>("Scope")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SCOPE");

                    b.Property<DateTime?>("SleepUntil")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("SLEEPUNTIL");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("STARTTIME");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STATUS");

                    b.Property<int>("StepId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STEPID");

                    b.Property<string>("StepName")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("STEPNAME");

                    b.Property<long>("WorkflowId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("WORKFLOWID");

                    b.HasKey("PersistenceId");

                    b.HasIndex("WorkflowId");

                    b.ToTable("WF_EXECUTIONPOINTER", "HLV_EMAIL_PRO");
                });

            modelBuilder.Entity("WorkflowCore.Persistence.EntityFramework.Models.PersistedExtensionAttribute", b =>
                {
                    b.Property<long>("PersistenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("PERSISTENCEID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PersistenceId"));

                    b.Property<string>("AttributeKey")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("ATTRIBUTEKEY");

                    b.Property<string>("AttributeValue")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ATTRIBUTEVALUE");

                    b.Property<long>("ExecutionPointerId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("EXECUTIONPOINTERID");

                    b.HasKey("PersistenceId");

                    b.HasIndex("ExecutionPointerId");

                    b.ToTable("WF_EXTENSIONATTRIBUTE", "HLV_EMAIL_PRO");
                });

            modelBuilder.Entity("WorkflowCore.Persistence.EntityFramework.Models.PersistedScheduledCommand", b =>
                {
                    b.Property<long>("PersistenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("PERSISTENCEID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PersistenceId"));

                    b.Property<string>("CommandName")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("COMMANDNAME");

                    b.Property<string>("Data")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DATAVALUE");

                    b.Property<long>("ExecuteTime")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("EXECUTETIME");

                    b.HasKey("PersistenceId");

                    b.HasIndex("ExecuteTime");

                    b.HasIndex("CommandName", "Data")
                        .IsUnique()
                        .HasFilter("\"COMMANDNAME\" IS NOT NULL AND \"DATAVALUE\" IS NOT NULL");

                    b.ToTable("WF_SCHEDULEDCOMMAND", "HLV_EMAIL_PRO");
                });

            modelBuilder.Entity("WorkflowCore.Persistence.EntityFramework.Models.PersistedSubscription", b =>
                {
                    b.Property<long>("PersistenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("PERSISTENCEID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PersistenceId"));

                    b.Property<string>("EventKey")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("EVENTKEY");

                    b.Property<string>("EventName")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("EVENTNAME");

                    b.Property<string>("ExecutionPointerId")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("EXECUTIONPOINTERID");

                    b.Property<string>("ExternalToken")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("EXTERNALTOKEN");

                    b.Property<DateTime?>("ExternalTokenExpiry")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("EXTERNALTOKENEXPIRY");

                    b.Property<string>("ExternalWorkerId")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("EXTERNALWORKERID");

                    b.Property<int>("StepId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STEPID");

                    b.Property<DateTime>("SubscribeAsOf")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("SUBSCRIBEASOF");

                    b.Property<string>("SubscriptionData")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SUBSCRIPTIONDATA");

                    b.Property<Guid>("SubscriptionId")
                        .HasMaxLength(200)
                        .HasColumnType("RAW(16)")
                        .HasColumnName("SUBSCRIPTIONID");

                    b.Property<string>("WorkflowId")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("WORKFLOWID");

                    b.HasKey("PersistenceId");

                    b.HasIndex("EventKey");

                    b.HasIndex("EventName");

                    b.HasIndex("SubscriptionId")
                        .IsUnique();

                    b.ToTable("WF_SUBSCRIPTION", "HLV_EMAIL_PRO");
                });

            modelBuilder.Entity("WorkflowCore.Persistence.EntityFramework.Models.PersistedWorkflow", b =>
                {
                    b.Property<long>("PersistenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("PERSISTENCEID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PersistenceId"));

                    b.Property<DateTime?>("CompleteTime")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("COMPLETETIME");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATETIME");

                    b.Property<string>("Data")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DATAVALUE");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<Guid>("InstanceId")
                        .HasMaxLength(200)
                        .HasColumnType("RAW(16)")
                        .HasColumnName("INSTANCEID");

                    b.Property<long?>("NextExecution")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("NEXTEXECUTION");

                    b.Property<string>("Reference")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("REFERENCE");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STATUS");

                    b.Property<int>("Version")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("VERSION");

                    b.Property<string>("WorkflowDefinitionId")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("WORKFLOWDEFINITIONID");

                    b.HasKey("PersistenceId");

                    b.HasIndex("InstanceId")
                        .IsUnique();

                    b.HasIndex("NextExecution");

                    b.ToTable("WF_WORKFLOW", "HLV_EMAIL_PRO");
                });

            modelBuilder.Entity("WorkflowCore.Persistence.EntityFramework.Models.PersistedExecutionPointer", b =>
                {
                    b.HasOne("WorkflowCore.Persistence.EntityFramework.Models.PersistedWorkflow", "Workflow")
                        .WithMany("ExecutionPointers")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("WorkflowCore.Persistence.EntityFramework.Models.PersistedExtensionAttribute", b =>
                {
                    b.HasOne("WorkflowCore.Persistence.EntityFramework.Models.PersistedExecutionPointer", "ExecutionPointer")
                        .WithMany("ExtensionAttributes")
                        .HasForeignKey("ExecutionPointerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExecutionPointer");
                });

            modelBuilder.Entity("WorkflowCore.Persistence.EntityFramework.Models.PersistedExecutionPointer", b =>
                {
                    b.Navigation("ExtensionAttributes");
                });

            modelBuilder.Entity("WorkflowCore.Persistence.EntityFramework.Models.PersistedWorkflow", b =>
                {
                    b.Navigation("ExecutionPointers");
                });
#pragma warning restore 612, 618
        }
    }
}
